/// Multi-language localization dictionary for Thai and English
class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _values = {
    'th': {
      // General
      'appName': 'Finclub',
      'tagline': 'เครื่องมือคำนวณและวางแผนสินเชื่อที่ออกแบบมาเพื่อคุณ',
      'next': 'ถัดไป',
      'back': 'ย้อนกลับ',
      'cancel': 'ยกเลิก',
      'confirm': 'ยืนยัน',
      'ok': 'ตกลง',
      'success': 'สำเร็จ',
      'error': 'ข้อผิดพลาด',
      'loading': 'กำลังดำเนินการ...',
      'perDay': '/ วัน',

      // Navigation Tabs
      'navCalculator': 'คำนวณสินเชื่อ',
      'navSchedule': 'ตารางผ่อน',
      'navSavedPlans': 'บันทึก',
      'navProductInfo': 'เงื่อนไขและข้อมูล',

      // Language Selection Screen
      'selectLanguageTitle': 'เลือกภาษาที่ต้องการใช้งาน',
      'selectLanguageSubtitle': 'Select your preferred language',
      'thai': 'ภาษาไทย (Thai)',
      'english': 'English (อังกฤษ)',
      'continueToApp': 'ถัดไปเพื่อเริ่มต้นใช้งาน',

      // Welcome Screen
      'welcomeTitle': 'ยินดีต้อนรับสู่ Finclub',
      'welcomeSubtitle': 'เครื่องมือคำนวณดอกเบี้ยและวางแผนทางการเงินเบื้องต้น',
      'registerBtn': 'สมัครสมาชิก',
      'loginBtn': 'เข้าสู่ระบบ',
      'alreadyHaveAccount': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
      'dontHaveAccount': 'ยังไม่มีบัญชี? สมัครสมาชิก',

      // Register Screen
      'registerTitle': 'สร้างบัญชีสมาชิก Finclub',
      'registerSubtitle': 'กรอกข้อมูลเพื่อสมัครสมาชิกและบันทึกแผนคำนวณ',
      'emailLabel': 'อีเมล (Email)',
      'emailHint': 'example@email.com',
      'passwordLabel': 'รหัสผ่าน (Password)',
      'passwordHint': 'อย่างน้อย 8 ตัวอักษร',
      'rePasswordLabel': 'ยืนยันรหัสผ่าน (Re-password)',
      'rePasswordHint': 'กรอกรหัสผ่านเดิมอีกครั้ง',
      'uploadAvatar': 'อัพโหลดรูปโปรไฟล์',
      'changeAvatar': 'เปลี่ยนรูปโปรไฟล์',
      'avatarHint': 'แตะเพื่อเลือกรูปภาพจากกล้องหรือคลังภาพ',
      'passwordRulesTitle': 'เงื่อนไขความปลอดภัยของรหัสผ่าน:',
      'ruleUppercase': 'มีตัวพิมพ์ใหญ่ (A-Z) อย่างน้อย 1 ตัว',
      'ruleLowercase': 'มีตัวพิมพ์เล็ก (a-z) อย่างน้อย 1 ตัว',
      'ruleNumber': 'มีตัวเลข (0-9) อย่างน้อย 1 ตัว',
      'ruleSpecial': r'มีอักขระพิเศษ (@, $, !, %, *, ?, &, #) อย่างน้อย 1 ตัว',
      'ruleLength': 'ความยาวอย่างน้อย 8 ตัวอักษร',
      'passwordsNotMatch': 'รหัสผ่านและการยืนยันรหัสผ่านไม่ตรงกัน',
      'chooseFromGallery': 'เลือกจากคลังรูปภาพ',
      'takePhoto': 'ถ่ายภาพด้วยกล้อง',

      // Login Screen
      'loginTitle': 'เข้าสู่ระบบสมาชิก',
      'loginSubtitle': 'กรอกอีเมลและรหัสผ่านเพื่อเข้าใช้งาน',
      'loginSuccess': 'เข้าสู่ระบบสำเร็จ ยินดีต้อนรับกลับ',

      // Terms and Conditions Dialog
      'termsTitle': 'ข้อกำหนดและเงื่อนไขการใช้บริการ',
      'termsSubtitle': 'กรุณาอ่านและยอมรับข้อกำหนดก่อนเริ่มใช้งานสินเชื่อ Finclub',
      'termsCheckbox': 'ข้าพเจ้าได้อ่านและยอมรับข้อกำหนดและเงื่อนไขการให้บริการของ Finclub ทุกประการ',
      'termsAcceptBtn': 'ยอมรับข้อตกลงและเข้าสู่ระบบ',
      'termsWarning': 'กรุณาติ๊กยอมรับข้อกำหนดก่อนดำเนินการต่อ',

      // PIN & Biometric Authentication
      'pinTitle': 'กรุณากรอกรหัส PIN 6 หลัก',
      'pinSetupTitle': 'ตั้งรหัส PIN 6 หลัก',
      'pinSetupSubtitle': 'สร้างรหัส PIN 6 หลักเพื่อความปลอดภัยในการเข้าใช้งาน',
      'pinConfirmTitle': 'ยืนยันรหัส PIN 6 หลัก',
      'pinConfirmSubtitle': 'กรอกรหัส PIN 6 หลักเดิมอีกครั้งเพื่อยืนยัน',
      'pinNotMatch': 'รหัส PIN ไม่ตรงกัน กรุณาตั้งค่าใหม่อีกครั้ง',
      'pinInvalid': 'รหัส PIN ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง',
      'pinSuccess': 'ตั้งรหัส PIN สำเร็จเรียบร้อยแล้ว',
      'biometricPromptTitle': 'เปิดใช้งานสแกนลายนิ้วมือ',
      'biometricPromptSubtitle': 'เข้าสู่ระบบได้สะดวกรวดเร็วและปลอดภัยยิ่งขึ้นด้วยลายนิ้วมือหรือระบบชีวมิติ',
      'enableBiometric': 'เปิดใช้งาน',
      'skipBiometric': 'ข้ามไปก่อน',
      'biometricReason': 'สแกนลายนิ้วมือเพื่อเข้าสู่ระบบ Finclub',
      'biometricFailed': 'การสแกนลายนิ้วมือไม่สำเร็จ กรุณากรอกรหัส PIN',
      'usePinInstead': 'ใช้รหัส PIN แทน',
      'switchAccount': 'เข้าสู่ระบบด้วยบัญชีอื่น',

      // Security Settings Modal & Account Compliance
      'securityTitle': 'ความปลอดภัยและความเป็นส่วนตัว',
      'changePin': 'เปลี่ยนรหัส PIN 6 หลัก',
      'setPin': 'ตั้งค่ารหัส PIN 6 หลัก',
      'changePinSubtitle': 'แก้ไขรหัสผ่าน PIN สำหรับยืนยันตัวตน',
      'setPinSubtitle': 'ตั้งรหัส PIN เพื่อความปลอดภัยในการเข้าใช้งาน',
      'biometricTitle': 'สแกนลายนิ้วมือ / Face ID',
      'biometricSubtitle': 'เข้าสู่ระบบสะดวกรวดเร็วด้วยลายนิ้วมือ',
      'biometricEnabledToast': 'เปิดใช้งานสแกนลายนิ้วมือแล้ว',
      'biometricDisabledToast': 'ปิดใช้งานสแกนลายนิ้วมือแล้ว',
      'switchLanguage': 'เปลี่ยนภาษา / Switch Language',
      'deleteAccount': 'ลบบัญชีผู้ใช้',
      'deleteAccountSubtitle': 'ลบข้อมูลโปรไฟล์และประวัติการคำนวณทั้งหมดออกจากระบบถาวร',
      'deleteAccountConfirmTitle': 'ยืนยันการลบบัญชีผู้ใช้ถาวร',
      'deleteAccountConfirmMsg': 'คุณแน่ใจหรือไม่ว่าต้องการลบบัญชีผู้ใช้นี้?\n\nการดำเนินการนี้จะลบข้อมูลบัญชี ข้อมูลส่วนบุคคล ประวัติการคำนวณ และแผนที่บันทึกไว้ทั้งหมดออกจากเซิร์ฟเวอร์ และไม่สามารถกู้คืนได้อีกต่อไป',
      'deleteAccountSuccess': 'ลบบัญชีผู้ใช้ของคุณเรียบร้อยแล้ว',
      'disclaimerTitle': 'ข้อสงวนสิทธิ์ (Disclaimer)',
      'disclaimerContent': 'แอปพลิเคชันนี้เป็นเพียงเครื่องมือคำนวณและจำลองภาระดอกเบี้ยเบื้องต้นเพื่อการวางแผนทางการเงินเท่านั้น ไม่ได้มีบริการปล่อยสินเชื่อหรือเป็นตัวแทนจัดหาเงินกู้จริงแต่อย่างใด',

      // Product Banner
      'bannerTitle': 'คำนวณแผน 7 วัน',
      'bannerSubtitle': 'จำลองภาระดอกเบี้ยรายวันตามจริง วงเงินสูงสุด 50,000 บาท',
      'viewProductInfo': 'ดูเงื่อนไขการคำนวณ',
      'creditLimit': 'วงเงินจำลอง',
      'maxAmount': 'สูงสุด 50,000 ฿',
      'amountRangeShort': 'เลือกได้ 1k-50k',
      'interestRate': 'อัตราดอกเบี้ย',
      'maxRatePerYear': 'สูงสุด 35.80% / ปี',
      'calcDaily': 'คำนวณรายวัน',
      'tenure': 'ระยะเวลาผ่อน',
      'tenureFixedDays': 'คงที่ 7 วัน',
      'tenureOneTime': 'คำนวณรอบ 7 วัน',

      // 7-Day Loan Calculator Main Screen
      'loan7DaysTitle': 'เครื่องมือคำนวณแผน 7 วัน',
      'loan7DaysSubtitle': 'ระยะเวลาคงที่ 7 วัน แสดงสูตรและยอดชัดเจน โปร่งใส',
      'selectAmount': 'เลือกวงเงินที่ต้องการจำลองคำนวณ',
      'amountRange': 'วงเงิน 1,000 - 50,000 บาท',
      'tenureFixedBadge': 'รอบคำนวณ 7 วัน',
      'principalLabel': 'วงเงินที่คำนวณ',
      'dailyInterestLabel': 'ดอกเบี้ยต่อวัน',
      'sevenDaysInterestLabel': 'ดอกเบี้ยรวม 7 วัน',
      'revenueFeeLabel': 'ค่าดำเนินการประมาณการ',
      'totalRepaymentLabel': 'ยอด Total รวมประมาณการ',
      'dueDateLabel': 'ครบกำหนดชำระรอบ 7 วัน',
      'apply7DayLoanBtn': 'จำลองผลการประเมินสินเชื่อ',
      'applySuccessTitle': 'จำลองการคำนวณสำเร็จ!',
      'applySuccessMsg': 'ระบบได้แสดงผลจำลองการคำนวณและภาระดอกเบี้ยเบื้องต้นของคุณเรียบร้อยแล้ว (ไม่ใช่การกู้ยืมจริง)',
      'receiptTitle': 'สรุปผลจำลองแผนคำนวณ 7 วัน',
      'confirmApplyTitle': 'ยืนยันการจำลองแผนคำนวณ 7 วัน',
      'confirmApplyMsg': 'กรุณาตรวจสอบรายละเอียดก่อนดูผลการจำลอง:',
      'confirmApplyBtn': 'ดูผลลัพธ์จำลอง',

      // Schedule & Compare Tab
      'scheduleTabTitle': 'ตารางผ่อนชำระ 7 วัน & บันทึกแผน',
      'compareAmounts': 'เปรียบเทียบวงเงิน',
      'compareSubtitle': 'เปรียบเทียบดอกเบี้ยและยอด Total รวม 7 วัน (แตะเพื่อเลือกวงเงิน)',
      'savePlanBtn': 'บันทึกแผนนี้',
      'viewSavedBtn': 'ดูรายการที่บันทึก',
      'savePlanModalTitle': 'บันทึกแผนคำนวณ 7 วัน',
      'savePlanModalSubtitle': 'บันทึกเพื่อนำกลับมาดูหรือเปรียบเทียบในภายหลัง',
      'planNameLabel': 'ชื่อแผน',
      'planNameHint': 'เช่น ค่าใช้จ่ายฉุกเฉิน 7 วัน',
      'planNoteLabel': 'บันทึกข้อความเพิ่มเติม (ไม่บังคับ)',
      'planNoteHint': 'เช่น กู้สำหรับค่าซ่อมรถ',
      'planSavedSuccess': 'บันทึกแผนเรียบร้อยแล้ว',
      'shareSchedule': 'แชร์ตารางผ่อน',
      'shareSuccess': 'แชร์สรุปตารางผ่อน 7 วันเรียบร้อยแล้ว',
      'totalSevenDaysNote': 'ยอดรวม (7 วัน)',
      'interestAndFeeNote': 'ดอกเบี้ย',

      // Schedule Table
      'colDay': 'วันที่',
      'colDailyInterest': 'ดอกเบี้ย/วัน',
      'colAccruedInterest': 'ดอกเบี้ยสะสม',
      'colPaymentDue': 'ยอดที่ต้องชำระ',
      'dayPrefix': 'วันที่',
      'dayDue': 'ครบกำหนดชำระ',
      'scheduleSummaryNote': 'ชำระคืนเงินต้นพร้อมดอกเบี้ยและค่าดำเนินการครบกำหนดในวันที่ 7',
      'totalRepaymentNote': 'ยอด Total รวม (เงินต้น + ดอกเบี้ย 7 วัน + ค่าดำเนินการ)',

      // Saved Loans Screen
      'savedLoansTitle': 'รายการบันทึกแผนสินเชื่อ 7 วัน',
      'refreshData': 'รีเฟรชข้อมูล',
      'totalPlansCount': 'จำนวนแผนที่บันทึก',
      'itemsUnit': 'รายการ',
      'avgPlanAmount': 'วงเงินเฉลี่ยต่อแผน',
      'savedPlansHeader': 'แผนคำนวณ 7 วันที่บันทึกไว้',
      'emptySavedTitle': 'ยังไม่มีแผนคำนวณ 7 วันที่บันทึกไว้',
      'emptySavedSubtitle': 'เมื่อคุณคำนวณสินเชื่อ 7 วันในหน้าตารางผ่อนแล้ว สามารถกดปุ่มบันทึกเพื่อเก็บเข้าสู่ฐานข้อมูล MySQL ส่วนตัวของคุณได้ที่นี่',
      'goToScheduleBtn': 'ไปหน้าตารางผ่อน 7 วัน',
      'deletePlanTooltip': 'ลบแผนนี้',
      'deletePlanModalTitle': 'ยืนยันการลบแผนคำนวณ',
      'deletePlanModalContent': 'คุณต้องการลบแผนนี้ออกจากฐานข้อมูลใช่หรือไม่?\n\nเมื่อลบแล้วจะไม่สามารถกู้คืนข้อมูลนี้ได้',
      'deleteConfirmBtn': 'ยืนยันการลบ',
      'deleteSuccessToast': 'ลบรายการบันทึกออกจากฐานข้อมูลเรียบร้อย',
      'viewScheduleBtn': 'ดูตารางผ่อน',
      'usePlanBtn': 'ใช้แผนนี้',
      'planLoadedToast': 'โหลดแผนเข้าเครื่องคำนวณแล้ว',

      // Schedule Detail Screen
      'scheduleDetailTitle': 'ตารางผ่อนชำระ 7 วัน',
      'scheduleDetailHeader': 'รายละเอียดตารางชำระรายวัน (7 วัน)',
      'totalDueOnDay7': 'ชำระคืนยอดรวม',

      // Product Info Screen
      'productInfoTitle': 'ข้อมูลผลิตภัณฑ์ & เงื่อนไข',
      'productHighlightTitle': 'จุดเด่นผลิตภัณฑ์สินเชื่อ Finclub 7 วัน',
      'productHighlightDesc': 'สินเชื่อหมุนเวียนระยะสั้น 7 วัน ออกแบบมาเพื่อเพิ่มสภาพคล่องทางการเงินฉุกเฉิน อนุมัติรวดเร็ว ดอกเบี้ยรายวันตามจริง โปร่งใส',
      'featureLoanAmountTitle': 'วงเงินสินเชื่อ',
      'featureLoanAmountDesc': 'สูงสุด 50,000 บาท (เริ่มต้น 1,000 บาท)',
      'featureInterestRateTitle': 'อัตราดอกเบี้ย',
      'featureInterestRateDesc': '35.80% ต่อปี (คำนวณรายวันตามยอดกู้จริง)',
      'featureTenureTitle': 'ระยะเวลาผ่อนชำระ',
      'featureTenureDesc': 'คงที่ 7 วัน ชำระคืนครั้งเดียวครบกำหนด',
      'featureFeeTitle': 'ค่าธรรมเนียมดำเนินการ',
      'featureFeeDesc': 'ขั้นต่ำ 50 บาท (1% ของเงินต้น)',
      'calcFormulaTitle': 'สูตรและวิธีการคำนวณสินเชื่อ 7 วัน',
      'formulaDailyInterest': 'ดอกเบี้ยต่อวัน = เงินต้น x (35.80% / 100) / 365',
      'formulaTotalInterest': 'ดอกเบี้ยรวม 7 วัน = ดอกเบี้ยต่อวัน x 7',
      'formulaTotalRepayment': 'ยอดรวมชำระ = เงินต้น + ดอกเบี้ย 7 วัน + ค่าดำเนินการ',
      'applicantQualificationTitle': 'คุณสมบัติผู้สมัคร',
      'qualAge': 'สัญชาติไทย อายุ 20 - 65 ปีบริบูรณ์',
      'qualIncome': 'มีรายได้ประจำหรือประกอบอาชีพอิสระที่ตรวจสอบได้',
      'qualAccount': 'มีบัญชีเงินฝากธนาคารสำหรับรับโอนเงินกู้',
      'documentsTitle': 'เอกสารประกอบการพิจารณา',
      'docIdCard': 'บัตรประจำตัวประชาชนตัวจริงที่ยังไม่หมดอายุ',
      'docBankStatement': 'รายการเดินบัญชีธนาคารย้อนหลัง 3 - 6 เดือน',
      'faqTitle': 'คำถามที่พบบ่อย (FAQ)',
      'faq1Q': 'สินเชื่อ 7 วัน มีค่าธรรมเนียมแอบแฝงหรือไม่?',
      'faq1A': 'ไม่มีค่าธรรมเนียมแอบแฝงใดๆ ยอดที่ต้องชำระทั้งหมดประกอบด้วย เงินต้น ดอกเบี้ยรายวัน และค่าดำเนินการ ซึ่งแสดงให้เห็นครบถ้วนก่อนยื่นขอกู้',
      'faq2Q': 'สามารถชำระคืนก่อนกำหนด 7 วันได้หรือไม่?',
      'faq2A': 'สามารถชำระคืนก่อนกำหนดได้ตลอดเวลา โดยดอกเบี้ยจะคิดตามจำนวนวันที่ใช้งานจริง',
      'faq3Q': 'อนุมัติและโอนเงินเข้าบัญชีเร็วแค่ไหน?',
      'faq3A': 'ระบบพิจารณาอัตโนมัติรวดเร็ว โอนเงินเข้าบัญชีธนาคารของคุณทันทีที่ได้รับอนุมัติ',

      // Trust Footer
      'trustFooterTitle': 'เงื่อนไขสินเชื่อ 7 วัน (Fixed 7-Day Terms)',
      'trustFooterDesc': '• สินเชื่อระยะเวลาผ่อนชำระคงที่ 7 วัน แสดงยอดเงินต้น ดอกเบี้ยรายวัน ค่าดำเนินการ และยอดรวมที่ต้องชำระอย่างโปร่งใส\n• อัตราดอกเบี้ยสูงสุดไม่เกิน 35.80% ต่อปีตามเกณฑ์ธนาคารแห่งประเทศไทย\n• ชำระคืนภายใน 7 วันเพื่อรักษาสถานะเครดิตที่ดี',

      // Profile & User Info
      'profileTitle': 'ข้อมูลผู้ใช้งาน',
      'logout': 'ออกจากระบบ',
      'logoutConfirm': 'คุณต้องการออกจากระบบหรือไม่?',
      'termsAcceptedBadge': 'ยอมรับเงื่อนไขแล้ว',
    },
    'en': {
      // General
      'appName': 'Finclub',
      'tagline': 'Smart Loan & Interest Calculator',
      'next': 'Next',
      'back': 'Back',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'ok': 'OK',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Processing...',
      'perDay': '/ day',

      // Navigation Tabs
      'navCalculator': 'Calculator',
      'navSchedule': 'Schedule',
      'navSavedPlans': 'Saved Plans',
      'navProductInfo': 'Terms & Info',

      // Language Selection Screen
      'selectLanguageTitle': 'Select Your Language',
      'selectLanguageSubtitle': 'Choose your preferred language to get started',
      'thai': 'ภาษาไทย (Thai)',
      'english': 'English',
      'continueToApp': 'Next to Continue',

      // Welcome Screen
      'welcomeTitle': 'Welcome to Finclub',
      'welcomeSubtitle': 'Digital Financial Planning & Loan Calculator',
      'registerBtn': 'Register',
      'loginBtn': 'Log In',
      'alreadyHaveAccount': 'Already have an account? Log In',
      'dontHaveAccount': "Don't have an account? Register",

      // Register Screen
      'registerTitle': 'Create Finclub Account',
      'registerSubtitle': 'Sign up to calculate and save your financial plans',
      'emailLabel': 'Email Address',
      'emailHint': 'example@email.com',
      'passwordLabel': 'Password',
      'passwordHint': 'Min 8 characters',
      'rePasswordLabel': 'Confirm Password (Re-password)',
      'rePasswordHint': 'Re-enter your password',
      'uploadAvatar': 'Upload Profile Picture',
      'changeAvatar': 'Change Profile Picture',
      'avatarHint': 'Tap to pick image from camera or gallery',
      'passwordRulesTitle': 'Password Security Requirements:',
      'ruleUppercase': 'At least 1 uppercase letter (A-Z)',
      'ruleLowercase': 'At least 1 lowercase letter (a-z)',
      'ruleNumber': 'At least 1 numeric digit (0-9)',
      'ruleSpecial': r'At least 1 special character (@, $, !, %, *, ?, &, #)',
      'ruleLength': 'Minimum 8 characters in length',
      'passwordsNotMatch': 'Passwords do not match',
      'chooseFromGallery': 'Choose from Gallery',
      'takePhoto': 'Take a Photo',

      // Login Screen
      'loginTitle': 'Member Login',
      'loginSubtitle': 'Enter your email and password to log in',
      'loginSuccess': 'Logged in successfully. Welcome back!',

      // Terms and Conditions Dialog
      'termsTitle': 'Terms & Conditions',
      'termsSubtitle': 'Please review and accept terms before using Finclub services',
      'termsCheckbox': 'I have read and agree to all Finclub Terms of Service and Privacy Policy.',
      'termsAcceptBtn': 'Accept Terms & Continue',
      'termsWarning': 'Please check the box to accept terms and conditions.',

      // PIN & Biometric Authentication
      'pinTitle': 'Enter 6-Digit PIN',
      'pinSetupTitle': 'Set 6-Digit PIN',
      'pinSetupSubtitle': 'Create a 6-digit PIN for quick and secure access',
      'pinConfirmTitle': 'Confirm 6-Digit PIN',
      'pinConfirmSubtitle': 'Re-enter your 6-digit PIN to confirm',
      'pinNotMatch': 'PINs do not match. Please try again.',
      'pinInvalid': 'Incorrect PIN. Please try again.',
      'pinSuccess': 'PIN set successfully',
      'biometricPromptTitle': 'Enable Fingerprint / Face ID',
      'biometricPromptSubtitle': 'Log in faster and more securely using biometric authentication',
      'enableBiometric': 'Enable',
      'skipBiometric': 'Skip for now',
      'biometricReason': 'Scan fingerprint to authenticate Finclub',
      'biometricFailed': 'Biometric authentication failed. Please enter PIN.',
      'usePinInstead': 'Use PIN instead',
      'switchAccount': 'Log in with another account',

      // Security Settings Modal & Account Compliance
      'securityTitle': 'Security & Privacy',
      'changePin': 'Change 6-Digit PIN',
      'setPin': 'Set 6-Digit PIN',
      'changePinSubtitle': 'Update your authentication PIN code',
      'setPinSubtitle': 'Configure a 6-digit PIN for app security',
      'biometricTitle': 'Fingerprint / Face ID',
      'biometricSubtitle': 'Log in quickly and securely with biometrics',
      'biometricEnabledToast': 'Biometric login enabled',
      'biometricDisabledToast': 'Biometric login disabled',
      'switchLanguage': 'Switch Language / เปลี่ยนภาษา',
      'deleteAccount': 'Delete Account',
      'deleteAccountSubtitle': 'Permanently remove your account and all saved data',
      'deleteAccountConfirmTitle': 'Confirm Permanent Account Deletion',
      'deleteAccountConfirmMsg': 'Are you sure you want to permanently delete your account?\n\nThis will permanently delete your account, personal info, and all saved calculations from the server. This action cannot be undone.',
      'deleteAccountSuccess': 'Your account has been deleted successfully.',
      'disclaimerTitle': 'Legal Disclaimer',
      'disclaimerContent': 'This application is strictly a loan calculation and financial planning simulation tool. It does not provide, facilitate, or broker real loans or financial credit services.',

      // Product Banner
      'bannerTitle': '7-Day Plan Simulator',
      'bannerSubtitle': 'Simulate daily interest on loans up to 50,000 THB',
      'viewProductInfo': 'View Calculation Terms',
      'creditLimit': 'Simulated Limit',
      'maxAmount': 'Max 50,000 ฿',
      'amountRangeShort': '1k-50k THB',
      'interestRate': 'Interest Rate',
      'maxRatePerYear': 'Max 35.80% / Year',
      'calcDaily': 'Calculated daily',
      'tenure': 'Tenure',
      'tenureFixedDays': 'Fixed 7 Days',
      'tenureOneTime': '7-Day Calculation Cycle',

      // 7-Day Loan Calculator Main Screen
      'loan7DaysTitle': '7-Day Loan Calculator',
      'loan7DaysSubtitle': 'Fixed 7-day tenure with transparent calculation breakdown',
      'selectAmount': 'Select Amount to Simulate',
      'amountRange': 'Range: 1,000 - 50,000 THB',
      'tenureFixedBadge': '7-Day Cycle',
      'principalLabel': 'Calculated Amount',
      'dailyInterestLabel': 'Daily Interest',
      'sevenDaysInterestLabel': '7-Day Interest',
      'revenueFeeLabel': 'Estimated Service Fee',
      'totalRepaymentLabel': 'Estimated Total',
      'dueDateLabel': 'Due Date (7 Days)',
      'apply7DayLoanBtn': 'Simulate Loan Evaluation',
      'applySuccessTitle': 'Simulation Completed!',
      'applySuccessMsg': 'Estimated interest and calculation simulation generated successfully (Not a real loan).',
      'receiptTitle': '7-Day Calculation Simulation Summary',
      'confirmApplyTitle': 'Confirm 7-Day Plan Simulation',
      'confirmApplyMsg': 'Review calculation details before generating simulation results:',
      'confirmApplyBtn': 'View Simulation',

      // Schedule & Compare Tab
      'scheduleTabTitle': '7-Day Repayment Schedule & Saved Plans',
      'compareAmounts': 'Compare Limits',
      'compareSubtitle': 'Compare interest and total 7-day repayment (Tap to select)',
      'savePlanBtn': 'Save This Plan',
      'viewSavedBtn': 'View Saved Plans',
      'savePlanModalTitle': 'Save 7-Day Loan Plan',
      'savePlanModalSubtitle': 'Save to view or compare later in your saved plans',
      'planNameLabel': 'Plan Title',
      'planNameHint': 'e.g. Emergency 7-day expense',
      'planNoteLabel': 'Additional Note (Optional)',
      'planNoteHint': 'e.g. For vehicle repair',
      'planSavedSuccess': 'Plan saved successfully',
      'shareSchedule': 'Share Schedule',
      'shareSuccess': '7-Day schedule summary shared successfully',
      'totalSevenDaysNote': 'Total (7 Days)',
      'interestAndFeeNote': 'Interest',

      // Schedule Table
      'colDay': 'Day',
      'colDailyInterest': 'Interest/Day',
      'colAccruedInterest': 'Accrued Interest',
      'colPaymentDue': 'Payment Due',
      'dayPrefix': 'Day',
      'dayDue': 'Final Due Date',
      'scheduleSummaryNote': 'Repay principal, total interest, and platform fee on day 7',
      'totalRepaymentNote': 'Total Repayment (Principal + 7-Day Interest + Processing Fee)',

      // Saved Loans Screen
      'savedLoansTitle': 'Saved 7-Day Loan Plans',
      'refreshData': 'Refresh Data',
      'totalPlansCount': 'Total Saved Plans',
      'itemsUnit': 'plans',
      'avgPlanAmount': 'Average Loan Amount',
      'savedPlansHeader': 'Saved 7-Day Plans',
      'emptySavedTitle': 'No saved 7-day loan plans yet',
      'emptySavedSubtitle': 'Calculate a 7-day loan in the schedule tab, then tap save to store it in your personal MySQL database here.',
      'goToScheduleBtn': 'Go to 7-Day Schedule',
      'deletePlanTooltip': 'Delete this plan',
      'deletePlanModalTitle': 'Confirm Delete Plan',
      'deletePlanModalContent': 'Are you sure you want to delete this plan from the database?\n\nThis action cannot be undone.',
      'deleteConfirmBtn': 'Confirm Delete',
      'deleteSuccessToast': 'Plan deleted from database successfully',
      'viewScheduleBtn': 'View Schedule',
      'usePlanBtn': 'Use Plan',
      'planLoadedToast': 'Plan loaded into calculator',

      // Schedule Detail Screen
      'scheduleDetailTitle': '7-Day Repayment Schedule',
      'scheduleDetailHeader': 'Daily Repayment Breakdown (7 Days)',
      'totalDueOnDay7': 'Total Due',

      // Product Info Screen
      'productInfoTitle': 'Product Details & Terms',
      'productHighlightTitle': 'Finclub 7-Day Loan Key Highlights',
      'productHighlightDesc': 'Short-term 7-day revolving loan designed for emergency liquidity, instant approval, and transparent daily interest.',
      'featureLoanAmountTitle': 'Credit Limit',
      'featureLoanAmountDesc': 'Up to 50,000 THB (Starts from 1,000 THB)',
      'featureInterestRateTitle': 'Interest Rate',
      'featureInterestRateDesc': '35.80% p.a. (Calculated daily on actual borrowed amount)',
      'featureTenureTitle': 'Repayment Tenure',
      'featureTenureDesc': 'Fixed 7 Days, single lump-sum repayment',
      'featureFeeTitle': 'Platform / Processing Fee',
      'featureFeeDesc': 'Min 50 THB (1% of loan principal)',
      'calcFormulaTitle': '7-Day Loan Calculation Formulas',
      'formulaDailyInterest': 'Daily Interest = Principal x (35.80% / 100) / 365',
      'formulaTotalInterest': '7-Day Total Interest = Daily Interest x 7',
      'formulaTotalRepayment': 'Total Repayment = Principal + 7-Day Interest + Processing Fee',
      'applicantQualificationTitle': 'Applicant Qualifications',
      'qualAge': 'Thai nationality, age 20 - 65 years',
      'qualIncome': 'Regular income or verifiable freelance/business earnings',
      'qualAccount': 'Active Thai bank account for loan disbursement',
      'documentsTitle': 'Required Documents',
      'docIdCard': 'Valid Thai National Identification Card',
      'docBankStatement': 'Bank account statement (last 3 - 6 months)',
      'faqTitle': 'Frequently Asked Questions (FAQ)',
      'faq1Q': 'Are there any hidden fees with the 7-day loan?',
      'faq1A': 'No hidden fees whatsoever. All fees consist of principal, daily interest, and the platform fee, clearly displayed before submission.',
      'faq2Q': 'Can I repay early before the 7-day deadline?',
      'faq2A': 'Yes, you can repay early anytime. Interest is calculated based on the actual number of days utilized.',
      'faq3Q': 'How fast is approval and fund transfer?',
      'faq3A': 'Instant automated review and fund transfer to your registered bank account upon approval.',

      // Trust Footer
      'trustFooterTitle': '7-Day Loan Terms & Conditions',
      'trustFooterDesc': '• Fixed 7-day tenure micro loan with transparent breakdown: principal, daily interest, platform fee, and total repayment.\n• Annual interest rate capped at 35.80% per annum.\n• Repay on time within 7 days to maintain a great credit score.',

      // Profile & User Info
      'profileTitle': 'User Profile',
      'logout': 'Log Out',
      'logoutConfirm': 'Are you sure you want to log out?',
      'termsAcceptedBadge': 'Terms Accepted',
    },
  };

  /// Returns localized string by key and language code
  static String get(String key, {String lang = 'th'}) {
    final langMap = _values[lang] ?? _values['th']!;
    return langMap[key] ?? _values['th']![key] ?? key;
  }
}
